services:

  app:
    container_name: app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
      - ./volumes/media:/media
      - ./volumes/static:/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  db:
    container_name: database
    image: postgres:17-alpine
    env_file: .env.dev
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - ./volumes/media:/media
      - ./volumes/static:/static
    depends_on: [app]

  redis:
    container_name: redis
    image: redis:7.4-alpine
    restart: always
    volumes:
      - ./volumes/redis/data:/data
    ports:
      - '6379:6379'

  celery:
    container_name: celery
    build: .
    command: celery -A django_in_docker.celery worker -l info -B -c 4
    ports: []
    depends_on:
      - app
      - redis
