services:

  app:
    container_name: app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn django_in_docker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./volumes/media:/media
      - ./volumes/static:/static
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    expose:
      - 8000

  db:
    container_name: db
    image: postgres:17-alpine
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
